-- SQLite dump generated by export-auth-db.js
-- Source: C:\Users\Antonio\Documents\VSCODE\HTML\Projeto Gestão Atestados\Projeto Gestão Atestados\backend\data\auth.db

PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

CREATE TABLE password_reset_tokens (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
INSERT INTO "password_reset_tokens" ("id", "user_id", "token_hash", "expires_at", "used_at", "created_at") VALUES (1, 4, '443e9cbf18085e008e79c9a2d37508d7901f6723c1702b2b30daeeb73b12c3fb', '2026-07-28T01:59:36.144Z', NULL, '2026-07-28 01:29:36');

CREATE TABLE records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  turma TEXT NOT NULL,
  turno TEXT,
  motivo TEXT,
  data_entrega TEXT,
  data_inicio TEXT,
  hora_inicio TEXT,
  dia_inicio TEXT,
  data_termino TEXT,
  hora_termino TEXT,
  dia_termino TEXT,
  created_by INTEGER,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (1, 'Kaua F. de Oliveira', '3MEC2', 'Vespertino', 'Atestado', '13/03/2026', '13/03/2026', '', 'Sexta', '13/03/2026', '', 'Sexta', 1, '2026-07-27 19:37:55');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (2, 'Ronaia da S. Vieira', '4ET3', 'Vespertino', 'Atestado', '23/03/2026', '06/03/2026', '', 'Sexta', '06/03/2026', '', 'Sexta', 1, '2026-07-27 19:38:57');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (3, 'Kidver J. R. Almao', '4ET1', 'Matutino', 'Atestado', '03/06/2026', '25/05/2026', '', 'Segunda', '25/05/2026', '', 'Segunda', 1, '2026-07-27 19:40:12');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (5, 'Valdenesio V. Kreuch', '1ET1', 'Matutino', 'Declaração', '06/03/2026', '05/03/2026', '', 'Quinta', '05/03/2026', '', 'Quinta', 1, '2026-07-27 19:43:27');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (6, 'Reginaldo A. Lourenço', '3AUI3', 'Noturno', 'Atestado', '26/03/2026', '23/03/2026', '', 'Segunda', '24/03/2026', '', 'Terca', 1, '2026-07-27 21:00:31');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (7, 'Emyer Nicolas M.R.', '4EM3', 'Noturno', 'Atestado', '22/04/2026', '16/04/2026', '', 'Quinta', '17/04/2026', '', 'Sexta', 1, '2026-07-27 23:55:30');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (11, 'CAMILLI VITÓRIA DA SILVA', '3SEG', 'Noturno', 'Atestado', '08/04/2026', '08/04/2026', '', 'Quarta', '08/04/2026', '', 'Quarta', 1, '2026-07-28 00:58:32');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (12, 'MANUELA VITORIA', '3ADM', 'EMIEP', 'Atestado', '22/05/2026', '14/05/2026', '', 'Quinta', '14/05/2026', '', 'Quinta', 1, '2026-07-28 01:01:02');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (13, 'GIOVANA CAROLINA DE MEDEIRO', '3ADM', 'EMIEP', 'Atestado', '03/06/2026', '03/06/2026', '', 'Quarta', '03/06/2026', '', 'Quarta', 1, '2026-07-28 01:02:02');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (14, 'MARIA ISABEL DE FRANÇA SALES', '3MKT', 'EMIEP', 'Atestado', '16/03/2026', '10/03/2026', '', 'Terca', '11/03/2026', '', 'Quarta', 1, '2026-07-28 01:14:46');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (15, 'THUANNY AGRA PREBIANCA', '3RH2', 'EMIEP', 'Atestado', '10/04/2026', '30/03/2026', '', 'Segunda', '31/03/2026', '', 'Terca', 1, '2026-07-28 13:50:24');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (16, 'LETICIA RAISSA RIBEIRO COELHO', '3RH2', 'EMIEP', 'Atestado', '15/06/2026', '12/06/2026', '', 'Sexta', '12/06/2026', '', 'Sexta', 1, '2026-07-28 13:51:48');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (17, 'Valeria Eduarda T. Moraes', '1ADM3', 'Noturno', 'Atestado', '18/03/2026', '16/03/2026', '', 'Segunda', '17/03/2026', '', 'Terca', 1, '2026-07-28 14:07:41');
INSERT INTO "records" ("id", "nome", "turma", "turno", "motivo", "data_entrega", "data_inicio", "hora_inicio", "dia_inicio", "data_termino", "hora_termino", "dia_termino", "created_by", "created_at") VALUES (18, 'Viviane L. Neves Marcilio', '3ADM3', 'Noturno', 'Atestado', '11/03/2026', '02/03/2026', '', 'Segunda', '11/03/2026', '', 'Quarta', 1, '2026-07-28 14:23:32');

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  professor_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  city TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "users" ("id", "professor_name", "email", "password_hash", "city", "role", "created_at") VALUES (1, 'Administrador', 'admin123@profe.sed.sc.gov.br', '$2a$10$Q4Yzf5vYmjmJ8qzsQIftk.Rzrof4mqqWVGk8EgWXyWvdsnzVQ.RVO', 'Joinville', 'admin', '2026-07-27 19:22:48');
INSERT INTO "users" ("id", "professor_name", "email", "password_hash", "city", "role", "created_at") VALUES (2, 'Maria Helena', 'supervisao@profe.sed.sc.gov.br', '$2a$10$J/DUoYiuCJl.pDzFdh0Yp.9zQIJIdjCHDo4roCJCP/.Td9k1ZZjmC', 'Joinville', 'user', '2026-07-27 19:22:48');
INSERT INTO "users" ("id", "professor_name", "email", "password_hash", "city", "role", "created_at") VALUES (3, 'Ronnan', '375025@profe.sed.sc.gov.br', '$2a$10$KaKQpjK3ATwzaV0gi7HTeurioT.1lVpQrQyAZHVqlKzRaK3XYU/oi', 'Joinville', 'user', '2026-07-27 19:26:26');
INSERT INTO "users" ("id", "professor_name", "email", "password_hash", "city", "role", "created_at") VALUES (4, 'Antonio Dias', '398812@profe.sed.sc.gov.br', '$2a$10$Tevy9/btrSN9FH3Ns44mqO3LKZxewcoPL2FrjRunj7U5baY79dYvu', 'Joinville', 'user', '2026-07-27 20:28:03');
INSERT INTO "users" ("id", "professor_name", "email", "password_hash", "city", "role", "created_at") VALUES (5, 'Roberli', '652976@profe.sed.sc.gov.br', '$2a$10$mLqjX4tP95W9EOlnPDjXqeO8KP2Jlty.mBqnCILeK4Uy3Qm8GHNv2', 'Joinville', 'user', '2026-07-27 21:32:02');

COMMIT;