const fs = require('fs');
const path = require('path');
const Database = require('better-sqlite3');

const sourcePath = process.argv[2] || path.resolve(__dirname, '..', 'data', 'auth.db');
const outputPath = process.argv[3] || path.resolve(__dirname, '..', 'data', 'auth.dump.sql');

function quoteIdentifier(name) {
  return '"' + String(name).replace(/"/g, '""') + '"';
}

function serializeValue(value) {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value === 'boolean') {
    return value ? '1' : '0';
  }
  if (Buffer.isBuffer(value)) {
    return "X'" + value.toString('hex') + "'";
  }
  return "'" + String(value).replace(/'/g, "''") + "'";
}

function main() {
  const db = new Database(sourcePath, { readonly: true });
  const objects = db.prepare(
    `SELECT type, name, sql
     FROM sqlite_master
     WHERE type IN ('table', 'index', 'view', 'trigger')
       AND name NOT LIKE 'sqlite_%'
     ORDER BY CASE type
       WHEN 'table' THEN 0
       WHEN 'index' THEN 1
       WHEN 'view' THEN 2
       WHEN 'trigger' THEN 3
       ELSE 4
     END, name`
  ).all();

  const lines = [
    '-- SQLite dump generated by export-auth-db.js',
    '-- Source: ' + sourcePath,
    '',
    'PRAGMA foreign_keys = OFF;',
    'BEGIN TRANSACTION;',
    ''
  ];

  for (const object of objects) {
    if (!object.sql) {
      continue;
    }

    lines.push(object.sql + ';');

    if (object.type === 'table') {
      const columns = db.prepare('PRAGMA table_info(' + quoteIdentifier(object.name) + ')').all();
      if (columns.length > 0) {
        const columnList = columns.map((column) => quoteIdentifier(column.name)).join(', ');
        const rows = db.prepare('SELECT * FROM ' + quoteIdentifier(object.name)).all();

        for (const row of rows) {
          const values = columns.map((column) => serializeValue(row[column.name])).join(', ');
          lines.push(
            'INSERT INTO ' + quoteIdentifier(object.name) + ' (' + columnList + ') VALUES (' + values + ');'
          );
        }
      }

      lines.push('');
      continue;
    }

    lines.push('');
  }

  lines.push('COMMIT;');
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
  db.close();

  console.log('SQLite dump exported to ' + outputPath);
}

main();
